FROM node:lts as build

ARG API_URL=http://localhost:8001

ENV API=${API_URL}

WORKDIR /app
COPY ./ .
RUN npm install
RUN NODE_ENV=production npm run build


FROM nginx:stable as runtime

RUN rm /etc/nginx/conf.d/default.conf
COPY env_conf/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /app

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
