FROM python:3.11 as builder

RUN apt-get update && \
    apt-get install -y && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt


FROM python:3.11-slim as runtime

COPY --from=builder /usr/local/ /usr/local/

COPY . /app

WORKDIR /app

RUN adduser --uid 2001 --system --no-create-home app
USER app

EXPOSE 8080
CMD ["gunicorn", "app:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8080"]