FROM python:3.11 as builder

RUN apt-get update && \
    apt-get install -y && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt


FROM python:3.11-slim as runtime

COPY --from=builder /usr/local/ /usr/local/

COPY . /app

WORKDIR /app

RUN adduser --uid 801 --system --no-create-home app

RUN mkdir -p /data/images && chown app:app /data/images

USER app

EXPOSE 8080
CMD ["sh", "/app/entrypoint.sh"]