"""Lot_stock and dates nullables

Revision ID: 1a0416663dd1
Revises: cf16c63d0912
Create Date: 2024-12-16 15:49:57.531195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0416663dd1'
down_revision = 'cf16c63d0912'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lots', sa.Column('lot_stock', sa.Integer(), nullable=True))
    op.drop_column('Supplies', 'lot_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Supplies', sa.Column('lot_stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Lots', 'lot_stock')
    # ### end Alembic commands ###
