"""users

Revision ID: 1e0cca83a47d
Revises: e6f26b3809aa
Create Date: 2023-09-05 11:38:36.472131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0cca83a47d'
down_revision = 'e6f26b3809aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Token',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_toke', sa.String(), nullable=False),
    sa.Column('refresh_toke', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('access_toke')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Token')
    # ### end Alembic commands ###
