"""delete example table

Revision ID: 3fb55a80c582
Revises: 035b9767732e
Create Date: 2023-07-25 15:02:37.605537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb55a80c582'
down_revision = '035b9767732e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Example')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Example',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Example_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Example_pkey')
    )
    # ### end Alembic commands ###
