"""Added stock column to Lots table

Revision ID: 6080e4a58ad8
Revises: 246c8bca542b
Create Date: 2024-08-12 10:53:52.136827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6080e4a58ad8'
down_revision = '246c8bca542b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lots', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Lots', 'stock')
    # ### end Alembic commands ###
