"""Loans table is now related to Lots

Revision ID: 692723d5739f
Revises: 6080e4a58ad8
Create Date: 2024-09-04 14:10:46.177397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692723d5739f'
down_revision = '6080e4a58ad8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Loans', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('Loans', sa.Column('lot_id', sa.Integer(), nullable=False))
    op.add_column('Loans', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('Loans', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('Loans', sa.Column('state', sa.Boolean(), nullable=False))
    op.add_column('Loans', sa.Column('description', sa.String(), nullable=False))
    op.drop_constraint('Loans_equipment_id_fkey', 'Loans', type_='foreignkey')
    op.create_foreign_key(None, 'Loans', 'Lots', ['lot_id'], ['id'])
    op.drop_column('Loans', 'loan_end_date')
    op.drop_column('Loans', 'equipment_id')
    op.drop_column('Loans', 'loan_start_date')
    op.drop_column('Loans', 'loan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Loans', sa.Column('loan_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Loans_loan_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.add_column('Loans', sa.Column('loan_start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('Loans', sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Loans', sa.Column('loan_end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Loans', type_='foreignkey')
    op.create_foreign_key('Loans_equipment_id_fkey', 'Loans', 'Equipments', ['equipment_id'], ['id'])
    op.drop_column('Loans', 'description')
    op.drop_column('Loans', 'state')
    op.drop_column('Loans', 'end_date')
    op.drop_column('Loans', 'start_date')
    op.drop_column('Loans', 'lot_id')
    op.drop_column('Loans', 'id')
    # ### end Alembic commands ###
