"""Equipment relevant

Revision ID: 73ba1f09e47f
Revises: 99c7d3545a48
Create Date: 2024-10-07 15:46:16.514855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ba1f09e47f'
down_revision = '99c7d3545a48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Equipments', sa.Column('relevant', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Equipments', 'relevant')
    # ### end Alembic commands ###
