"""State column in Loans table set to type String

Revision ID: 78e2fd9aca91
Revises: 692723d5739f
Create Date: 2024-09-04 15:21:12.821973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e2fd9aca91'
down_revision = '692723d5739f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
