"""init

Revision ID: 87228c26103e
Revises: bc6a87295645
Create Date: 2023-07-25 13:43:26.533872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87228c26103e'
down_revision = 'bc6a87295645'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
