"""Added Lots stock column

Revision ID: 8ba240b9fc6a
Revises: 246c8bca542b
Create Date: 2024-08-11 17:43:06.359219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba240b9fc6a'
down_revision = '246c8bca542b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lots', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Lots', 'stock')
    # ### end Alembic commands ###
