"""loan table

Revision ID: 908177c5bbcb
Revises: ae37044d7a52
Create Date: 2024-04-22 12:06:25.600990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908177c5bbcb'
down_revision = 'ae37044d7a52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Loans',
    sa.Column('loan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('loan_start_date', sa.Date(), nullable=False),
    sa.Column('loan_end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['Equipments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Loans')
    # ### end Alembic commands ###
