"""Logs table

Revision ID: 921c415a0374
Revises: 9ea766df193f
Create Date: 2024-06-27 12:49:38.647221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921c415a0374'
down_revision = '9ea766df193f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_table', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Logs')
    # ### end Alembic commands ###
