"""System roles by module

Revision ID: 99c7d3545a48
Revises: 72d770ab01b4
Create Date: 2024-09-10 12:30:19.663671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c7d3545a48'
down_revision = '72d770ab01b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('System_Roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Role_Module_Relation',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('create', sa.Boolean(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('update', sa.Boolean(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['Modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['System_Roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'module_id')
    )
    op.add_column('Users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Users', 'System_Roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'role_id')
    op.drop_table('Role_Module_Relation')
    op.drop_table('System_Roles')
    op.drop_table('Modules')
    # ### end Alembic commands ###
