"""delete example table

Revision ID: ac5e13275a1f
Revises: 87228c26103e
Create Date: 2023-07-25 13:44:14.509241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5e13275a1f'
down_revision = '87228c26103e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Example')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Example',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Example_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Example_pkey')
    )
    # ### end Alembic commands ###
