"""supply group

Revision ID: b34c4ac29ab9
Revises: fa2c46b8b9ac
Create Date: 2023-09-25 17:24:28.072278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34c4ac29ab9'
down_revision = 'fa2c46b8b9ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups_has_Supplies',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supply_id'], ['Supplies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'supply_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Groups_has_Supplies')
    # ### end Alembic commands ###
