"""Supply cost optional

Revision ID: cf16c63d0912
Revises: 234a4114a7ae
Create Date: 2024-12-12 13:14:47.950332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf16c63d0912'
down_revision = '234a4114a7ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Suppliers_has_Supplies', 'cost',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Suppliers_has_Supplies', 'cost',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
