"""lot supply to stock

Revision ID: e94e31013110
Revises: 3fb55a80c582
Create Date: 2023-07-25 18:31:40.920062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94e31013110'
down_revision = '3fb55a80c582'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
