"""lot group

Revision ID: fa2c46b8b9ac
Revises: 1e0cca83a47d
Create Date: 2023-09-25 12:43:12.692622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2c46b8b9ac'
down_revision = '1e0cca83a47d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Lots', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Lots', 'Groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Lots', type_='foreignkey')
    op.drop_column('Lots', 'group_id')
    op.drop_table('Groups')
    # ### end Alembic commands ###
